### ISSUE TITLE
Add Blue Hydrogen/Hydrogen CCS for Methane Reforming Policy

### ISSUE THREAD

**Issue by oashmoore** [EnergyInnovation/eps-us#195]
Add a new policy to apply CCS to hydrogen produced through methane reformation to allow users to model "blue hydrogen." Users in Louisiana have asked for this and I think it would be helpful for other regions.

**Comment by jrissman** [comment]
Reminder: for the amount of hydrogen CCS that will be performed in the BAU case, see the Rhodium data referenced in issue #203.  This is non-duplicative, since only the non-hydrogen categories from Rhodium's data are being used in the BAU Industry sector CCS.

**Comment by jrissman** [comment]
This may entail adding "district heat and hydrogen" sector as an eligible sector in the CCS component.  We would need new policy levers that allow CCS to be applied to hydrogen production and to district heat production.  This may or may not require fully separating district heat and hydrogen into distinct elements of the "sector" subscript.

**Comment by robbieorvis** [comment]
Completed for 4.0
