### ISSUE TITLE
Use capacity factors for newly built wind and solar that increase over time

### ISSUE THREAD

**Issue by jrissman** [EnergyInnovation/eps-us#25]
Use capacity factors for newly built wind and solar (in elec/BECF) that increase over time, thereby reducing their dependence on flexibility points per unit energy they generate.  (Flexibility points are based on capacity, so higher capacity factor means more generation at the same level of flexibility points.)

Note that increases to the capacity factor for "newly built" plants will affect all plants at this quality tier (i.e. all plants built during the model run), not just plants built after a specific, future date.  The latter approach is not possible without implementing the tracking annual cohorts of power plants with a new "Age" or "Year Built" subscript.  Therefore, be careful to moderate increases in capacity factor to effectively spread these increases out across all plants already built during the model run.  (Preexisting plants at the start of the model run will not be affected, as they exist in a different quality tier.)

_Suggested by: Ramez Namm (11/3/2015)_

**Comment by robbieorvis** [comment]
Completed as part of 4.0 updates.
