### ISSUE TITLE
Bug with "Fuel Used for CCS by Electricity Sector"

### ISSUE THREAD

**Issue by oashmoore** [EnergyInnovation/eps-us#264]
Hi Jeff and Megan,

I think there's a bug in the current method for calculating "Fuel used for CCS by electricity sector." It takes total 'Energy used for CCS' and apportions it by electricity power plant type using 'Last year pollutants sequestered by electricity sector.' The issue I'm running into in a scenario is that the natural gas power plant use is set to zero in 2050, however it still has fuel consumption associated with it from running CCS due to the last year portion. So currently the CCS fuel consumption is greater than zero for the nat gas power plants while the fuel used for electricity generation is zero. 

I think @robbieorvis has ideas on how to fix it.

**Comment by mkmahajan** [comment]
This issue is no longer relevant no that we've redone the electricity sector CCS calculations.
