### ISSUE TITLE
Correct EIA fuel efficiency data with EPA data as a reference

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#265]
@dobrien13 and I noticed today that the new vehicle fuel efficiency values from EIA do not match reported fuel efficiency values from the EPA Automotive Trends Report: https://www.epa.gov/automotive-trends/highlights-automotive-trends-report.

The reason for this is that when EPA sets fuel efficiency values they allow for credits from non-efficiency components to help meet the standard. For example, of the total standard of 238 g CO2/mile from EPA, the efficiency component is actually at 272 g CO2/mile, and the rest of the reductions from there to meet the standard come from a mix of AC credits (for HFC reductions), "advanced tech credits", and off-cycle credits, 

In EIA's NEMS model, however, the model only knows how to adjust vehicle fuel efficiency to hit the EPA targets, so it over-complies on efficiency because it doesn't have the other options to reduce the equivalent g CO2/mile metric.

We should update our calculations for the efficiency calculations in the EPS to adjust the EIA data by the gap between the EIA data and the historical EPA data, so that we only model fuel efficiency impacts. The detailed trends data from EPA (Export G, here: https://www.epa.gov/automotive-trends/explore-automotive-trends-data#DetailedData) has the necessary data to make the adjustment.

**Comment by mkmahajan** [comment]
Mary Francis updated the data files for this issue, so I'm closing this out
