### ISSUE TITLE
Modify endogenous learning to multiply by previous year value, not start year value

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#272]
Currently, our endogenous learning functions take a start year value and multiply by that value to find cost changes in future years, and only do this when there are zero values in the input data for relevant costs.

We should consider slightly modifying the structure so that current year cost values are found relative to prior year cost values, instead of relative to start year values. This would allow us some flexibility in data sources, for example being able to switch from exogenous to endogenous learning and to do so without having a price jump.

This is increasingly important the in the wake of high inflation in over the past few years, where many technology prices have stagnated or even increase (e.g. solar PV and batteries). While we expect these technologies to resume their cost trends in the future, accounting for inflation of these technology prices in particular seems important. I don't believe technologies are being equally affected by inflation and so some technologies (batteries in particular) are experience more significant changes in costs than other commodities. We might need to adjust prices based on the inflation adjusted prices to remove this effect from modeling.

**Comment by mkmahajan** [comment]
I've set this up for vehicle battery prices. But before applying the same method to wind and solar prices, I'd like to briefly check with @jrissman to see if there's a more elegant way to handle it than what I came up with.
