### ISSUE TITLE
Handle power plant retrofitting

### ISSUE THREAD

**Issue by jrissman** [EnergyInnovation/eps-us#279]
We should consider adding cost-driven and/or policy-mandated retrofitting of power plants.  Historically, coal-to-gas retrofits were the most relevant use case for this model capability.  However, going forward, retrofitting may be important to allow non-CCS versions of plants to be retrofit to their CCS-equipped versions.

Retrofitting should be handled separately from costless fuel shifting and cofiring (which is covered in issue #278).  Retrofitting involves substantial new investment and should not just change the power plant type but should also update the vintage of those MW to the current year.  It involves capital spending that needs to be incorporated into cash flows.

Structurally, the retrofitting code should probably resemble the code to determine new, cost-effective capacity construction, but with different coefficients to calibrate, and only a couple permitted retrofitting paths (such as coal-to-gas, non-CCS-gas-to-CCS-gas, and non-CCS-coal-to-CCS-coal).  It should not need an allocation, it should just be driven by cost-effectiveness.  Optionally, there can also be a policy lever mandating a certain, minimum level of retrofits.

It might be easier to do this after adding a CCS-equipped plant types (#280 ).

**Comment by mkmahajan** [comment]
The NREL ATB has data for retrofitting both coal and gas plants with CCS, including additional CAPEX, maintenance costs, and heat rate penalty compared to pre-retrofit: https://atb.nrel.gov/electricity/2023/data
