### ISSUE TITLE
Break apart the rooftop solar policy by building type

### ISSUE THREAD

**Issue by robbieorvis** [EnergyInnovation/eps-us#293]
Request from Agora: Allow the rooftop solar policy to bet set by building type instead of one value across all buildings.

This seems to make sense given the different policies used and how it affects cash flows.

**Comment by dobrien13** [comment]
Addressed on branch "dev_bldgs"

Commit #d69fd93d adds a new lever with which the user can specify a minimum rooftop solar capacity target for the model to hit, subscripted by Building Type. This would satisfy the needs of Agora for Ff55 modeling.

The subsequent commit #097b2986 adds Building Type subscript to the "min share of electricity met with dist solar" lever. The lever's maximum stringency was lowered to 13%, as NREL estimates a total rooftop solar potential in the US of 39% (13% is 39% averaged across three Building Types). However, the actual max solar capacity of each Building Type is significantly different. That said, I would resort to the previous commit, which fills the needs of Agora, and leave this policy lever unsubscripted unless existing U.S. policies requiring a share of electricity come from distributed sources have the granularity of building type.

**Comment by robbieorvis** [comment]
Thanks for this.

Note that we do not release bespoke model versions, so we need to figure out what we need to incorporate, and then coalesce on that and integrate it into the develop branch. Happy to discuss further.

**Comment by dobrien13** [comment]
Addressed via an explicit capacity addition lever on 10/1 commit #bcb7a5a4
