### ISSUE TITLE
Formula in "New Vehicles by Subregion" fails to add ZEVs if no ZEVs of a given vehicle type and vehicle technology would have been deployed without the ZEV policy

### ISSUE THREAD

**Issue by jrissman** [EnergyInnovation/eps-us#304]
The variable `New Vehicles by Subregion` scales up ZEV sales and scales down non-ZEV sales to comply with a ZEV standard independently in each sub-region.  If there would be no non-ZEV sales, the additional vehicles are multiplied by zero, so it eliminates the sale of non-ZEV vehicles without adding ZEV vehicle sales to counterbalance it.  This affects the China iGDP model v3.4.9.1, where ZEV standards are being applied to all non-road vehicle types, which don't have any ZEV-compliant technology options that would be added without the ZEV policy.

**Comment by mkmahajan** [comment]
Fixed in commit 503364
