### ISSUE TITLE
Add Hydrogen Production by Technology graph to webtool

### ISSUE THREAD

**Issue by dobrien13** [EnergyInnovation/eps-us#309]
Agora request, if possible.

**Comment by robbieorvis** [comment]
It’s already there, just has to be enabled in WebAppData.

On Jul 12, 2024, at 8:16 AM, dobrien13 ***@***.***> wrote:

﻿

Agora request, if possible.

**Comment by dobrien13** [comment]
Aha, missed that. Thank you, Robbie :)
