### ISSUE TITLE
Check irregularities in fuels/BFPaT

### ISSUE THREAD

**Issue by jrissman** [EnergyInnovation/eps-us#315]
In testing the new code in the industry sector, I noticed that output for certain fuel-related industries (oil and gas extraction, refining, coal mining) has an odd spike in year 2022.  Here's ISIC 06, oil and gas extraction, economic output ($):

![Oil_and_Gas_Extr_Output](https://github.com/user-attachments/assets/c028af54-0b5a-4ca1-954f-ae4822a7b658)

That $70 billion spike might not look like much in context.  But it interferes with the code that deploys industrial equipment, which relies on economic output.  Here you can see that it is forced to deploy in 2022 alone equipment to supply about $80 billion of output - $10 billion to replace retiring equipment and $70 billion to cover the big spike in output.

![Oil_and_Gas_Extr_Output_by_Vintage](https://github.com/user-attachments/assets/ada92484-af65-4090-87e7-1693fa1d6bb9)

This is so much that it doesn't need to deploy any more equipment until 2028, and the equipment pool becomes dominated by a weirdly large amount of vintage 2022 equipment, an effect that persists through the end of the model run.

I traced the spike in output back to input data, specifically to the fuel price data in `fuels/BFPaT`.  For both fuel taxes and pretax fuel prices, there is a big run-up in prices in 2022 that then goes away over a couple years.

Here's pretax fuel price by sector from BFPaT:

![BAU_Pretax_Fuel_Price_by_Sector](https://github.com/user-attachments/assets/9acb7631-78c0-477f-a2d7-9fe22bb1c253)

Here's fuel tax per unit of fuel from BFPaT:

![BAU_Fuel_Tax_by_Sector](https://github.com/user-attachments/assets/ebda2bd1-a9a5-4749-90e7-13c4d298c350)

The data in the early years, around 2022, look odd.  Lots of fuels have both exceptionally high pretax prices and exceptionally high tax rates in that year, which quickly taper off.  This is causing the downstream effects that are complicating the vintaging of industrial equipment.  Do you think someone might check BFPaT to see if the transient jump in fuel prices and tax rates, across multiple fuel types, in 2022, is correct?

I know oil and gas prices--and therefore economic output from those industries--can legitimately be volatile and therefore is not an ideal guide to the amount of equipment those industries deploy each year.  I'll probably need to use some mechanism or adjustment to handle industrial equipment in these industries - maybe normalize against a fuel price index, or base equipment on BTUs rather than dollars of output.  I'll handle it in the new industry sector code.  But I just wanted to point out that BFPaT might benefit from a quick look-over.

(The sudden increase in the price and tax rate of hydrogen in 2033 is also visible in the last graph above.  That is not affecting industrial equipment.  It probably pertains to the IRA tax credit expiration.  The subsidy is contained within the pretax cost of hydrogen, so the fact that the tax rate jumps up when the subsidy goes away means the tax is based on a percentage of the after-subsidy purchase price, like a sales tax, and not an excise tax like the gasoline tax.  If this is what you expect to happen with sales taxes on hydrogen when the subsidy expires, that's fine, but I did want to point out that the tax rate is suddenly increasing when the subsidy goes away.)

**Comment by jrissman** [comment]
Here's another variable that is good at highlighting the fuel prices in early years of the run.  This is showing natural gas.  The most notable feature is a trough in natural gas prices centered on 2024.

![Pretax_Fuel_Cost_per_Unit_Energy_by_Sector](https://github.com/user-attachments/assets/bf41a84f-165f-4e75-9c79-fba1bee47a04)

**Comment by jrissman** [comment]
The fix in 533235c makes industrial equipment deployment in the fuel-supplying industries based on the volume of product they produce rather than economic revenue, so price fluctuations no longer erroneously affect equipment deployment.  Here's the updated graph of output by vintage for ISIC 06: oil and gas extraction.  This is how the graph is supposed to look, with deployment of new equipment in every year of the model run and a nice distribution across vintages.  (There still is a bump in 2022, but it's much smaller than before and is because a greater quantity of energy was actually sold that year relative to the previous year.)

![Fixed_Output_By_Equipment_Vintage](https://github.com/user-attachments/assets/aecaf88a-f0d1-4da4-85f7-e07f12ac17f8)

**Comment by jrissman** [comment]
I've updated to the Use EIA 2024 Monthly Densified Biomass Fuel Report as the data source for biomass prices.  Anyone who works on this issue (#315) should work from the updated BFPaT in branch develop_4.1.0, not from any older version of BFPaT, such as the one in 4.0.1, to avoid overwriting my changes.

**Comment by robbieorvis** [comment]
Hi Jeff,

You are correct about the price fluctuations, but those are based on empirical data. You'll recall that oil and gas prices shot through the roof with the Russian invasion of Ukraine, which is what is being captured here. We needed to capture these dynamics for a variety of reasons, so we need to keep the ability to use historical data in BFPaT, even when it is highly variable.

It sounds like maybe you have a workaround you developed. I'll also add that I had to come up with something for the electricity sector to deal with the same issue; i.e. a single year of high revenue could drive additions, even when it was planly obvious that was an aberrant year. To do this, I introduced a rolling five-year average price by converting BFPaT to use the FutureYear subscript instead its prior structure.

I would suggest you do something similar, if you need an improvement still, for industry, since as with the electricity sector, industrial investments will be decided based on anticipated future prices (commodities and fuels). You can see the structure I used in the electricity sector if you wish to copy it. I think it would be good to include some type of annual averaging regardless of which approach you use in order to smooth out weird annual fluctuations in energy prices.

**Comment by jrissman** [comment]
Yes, I addressed this in the new industrial sector, using a different approach than the one you used in the electricity sector.  If we observe a need for averaging energy prices in the industrial sector, I will implement price averaging at that time.

Since you reviewed BFPaT and believe it to be accurate, that's all this issue was opened for, so I'll close it now.
