### ISSUE TITLE
Include distributed solar in Share of Generation from Clean Sources

### ISSUE THREAD

**Issue by dobrien13** [EnergyInnovation/eps-us#323]
Low-priority request from Agora

**Comment by robbieorvis** [comment]
It is actually already included in that value. Megan and I were discussing yesterday.

From: dobrien13 ***@***.***>
Sent: Wednesday, August 21, 2024 10:19 AM
To: EnergyInnovation/eps-us ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EnergyInnovation/eps-us] Include distributed solar in Share of Generation from Clean Sources (Issue #323)


Low-priority request from Agora

-
