### ISSUE TITLE
Allow fuel price changes to drive industrial equipment efficiency improvements

### ISSUE THREAD

**Issue by jrissman** [EnergyInnovation/eps-us#8]
Allow changes in the fuel price caused by policies (like carbon tax, fuel taxes, and fuel price deregulation) to drive efficiency improvements in industrial equipment.

One approach is to adopt an elasticity of efficiency of industrial equipment with respect to fuel price.  This is best done as a long-term elasticity that influences a stock of industrial equipment that turns over, similar to the way the buildings sector is handled.  (The existing, short-term elasticity of production with respect to fuel prices would be retained.  This would be similar to how there are dual elasticities in the buildings sector, one for equipment and one for behavioral changes.)

**Comment by jrissman** [comment]
I built a working version of this, with structure shown below ([model file attached here](https://github.com/Energy-Innovation/eps-us/files/5514217/EPS.mdl.zip), based on EPS 3.1.0).

The first five variables, in the upper left, were pre-existing in 3.1.0 and were simply moved here.  The variable `Last Year Perc Change in Industrial Fuel Use from Price Efficiency Feedbacks` is the result of this whole calculation and feeds into `Perc Change in Industrial Fuel Use for Energy Purposes before Fuel Shifting at BAU Production Levels`.

![IndstEfficiencyCalcs](https://user-images.githubusercontent.com/7120106/98616364-84f2ea00-22b1-11eb-9adf-57eee221396d.PNG)

However, it’s proving to be really troublesome to find data on the elasticity of industrial energy efficiency upgrades with respect to energy price.  If you search for energy-related industrial elasticities, most of what you find are elasticities of demand for industrial products with respect to energy price.  I got a closer hit with [this 2018 EIA study, "Energy Efficiency and Price Responsiveness in Energy Intensive Chemicals Manufacturing"](https://www.eia.gov/analysis/studies/demand/industrial/chemicals/ei-eenprice/pdf/ee_chemicals_mfg.pdf), but they only seem to report the elasticity of energy use (energy demand) by industry with respect to energy price, which is a mix of things that can affect industrial energy use, not just equipment efficiency.  The elasticities they find in that study, -0.7 to -0.9, are too high to produce realistic results in the model structure I built.

There are also some downsides to using elasticities with respect to change in energy price (per unit energy), instead of energy cost (per unit industrial output), because we aren’t capturing the effects of other policies that affect energy consumption per unit output on the energy costs, like efficiency standards.  We are careful to do this in other sectors where we have these elasticities.  I think I might need to do this in industry too, even though it is harder here.  This involves understanding when we’ve fuel shifted vs. when we’ve just changed energy use.

It may be better to work on this issue together with issue #9, which concerns industrial price-driven fuel shifting.

**Comment by jrissman** [comment]
A separate note: [this paper](http://www.roiw.org/2008/2008-11.pdf) is a wonderful source for industrial equipment lifetimes (a piece of data we need).  See in particular Table 7 on page 255, reproduced below.  The first column contains codes for each industry - a key is in table 1 of the original paper.

![Table7](https://user-images.githubusercontent.com/7120106/98617133-30e90500-22b3-11eb-84cf-064aa0b8a228.PNG)

That same paper also has survival functions by age for industrial equipment (see Figure 2), which could allow for a more nuanced representation than a single average lifetime figure, if supported by annual age cohorts of industrial machinery in the EPS.

In case the link to the paper stops working, here's an attached copy: 
[2008-11.pdf](https://github.com/Energy-Innovation/eps-us/files/5514247/2008-11.pdf)

**Comment by jrissman** [comment]
Yes, that's right.  I think what we'll probably do is tackle #8 (price-driven efficiency gains) and #9 (price-driven fuel shifting) together, not for the EPS 3.1 release, but for a subsequent 3.x-series release, likely in 2021.  I thought I might be able to quickly tackle #8 on its own for inclusion in 3.1, but it proved to be a little to large/complex to squeeze into this release.  The working version I built above I plan to use as a reference when I return to this someday, but the final structure will look somewhat different, I expect.

I do think tracking industrial equipment (in units of annual energy consumption capacity) in a similar way to how we track vehicles or building components might become necessary.  We'll see.

**Comment by robbieorvis** [comment]
I believe this is the appropriate issue to discuss the stock turnover model for the industry sector.

BNEF has some excellent tools for estimating the profitability of low carbon industrial production. You can see how they approach this issue (screenshot below) using their tools.

![Capture](https://github.com/EnergyInnovation/eps-us/assets/45801289/fce05135-04a0-4ea5-bba8-cce93f574ac4)

Big picture:

1) Profitability for projects (retrofits and new) should be estimated and compared to a hurdle rate, which is the required internal rate of return necessary to invest in a project.

2) This can be achieved by computing an NPV for projects, including the cost of financing (debt and equity) and all capital and variable/O&M costs. You can add in any incentives of subsidies.

3) From there, you can calculate a project IRR and compare it to the hurdle IRR. If the project clears the hurdle IRR, its good to adopt, with higher project IRR/hurdle IRR ratios being more likely to see investment.

4) We might consider implementing something similar to what we do in the power sector or a two stage approach. New facilities (to replace retiring ones or meet new demand) could probably use a discrete choice function, like the logit model, to choose between options, or we could simply assign it to whatever has the best IRR. For retrofits, we might consider something more akin to what we have in the power sector, where we look at the cost of retrofitting and assume it affects some portion of the existing stock, based on how profitable it is and with diminishing returns. It may also be important to consider the remining lifetime of the facility, which could possibly be done by using a distribution to represent all the facilities in existence. 

5) Finally, we might need some way to represent demand for different commodities... we could do that by using ratios of GDP or some other metric. We probably need this to correctly forecast changes in demand for commodities under different policy scenarios and the fraction of that demand that can be met domestically.

**Comment by jrissman** [comment]
Completed. I think it's reasonably well-calibrated, but folks are of course free to try different logit coefficients if they want to see how it behaves when more or less sensitive to differences in prices between fuel types.  Closing this issue.

**Comment by dobrien13** [comment]
I'm reopening this issue as I've proposed a new methodology for BAU industrial equipment energy efficiency improvements, and need to make sure fuel price changes are properly incorporated into this implementation before re-closing. See the prior commit for details.

**Comment by dobrien13** [comment]
I'm reopening this issue as I've proposed a new methodology for BAU industrial equipment energy efficiency improvements, and need to make sure fuel price changes are properly incorporated into this implementation before re-closing. See the prior commit for details.

**Comment by dobrien13** [comment]
I've added back in the elasticity mechanism that Jeff originally proposed after finding some data for industry specifically rather than EIA data for commercial buildings originally used for lack of other sources. 

Elasticity from this paper from Josh Linn, now at RFF (linked in case helpful for others e.g. @jrissman):
https://onlinelibrary.wiley.com/doi/abs/10.1111/j.1468-0297.2008.02199.x
